#
# Copyright 2021 The Sigstore Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
- name: install docker dependencies
  apt: name=docker.io state=present

- name: start docker
  service: name=docker enabled=yes state=started

- name: download k0s
  get_url:
    url: https://github.com/k0sproject/k0s/releases/download/v0.12.0/k0s-v0.12.0-amd64
    dest: /usr/bin/k0s
    mode: '0755'

- name: install k0s
  shell:
    cmd: k0s install controller --single

- name: start and enable the k0s service
  service: name=k0scontroller enabled=yes state=started
